import { MD3DarkTheme, MD3LightTheme } from 'react-native-paper';
import Colors from '../constants/Colors';

// Create custom themes based on your color palette
export const paperThemes = {
  light: {
    ...MD3LightTheme,
    colors: {
      ...MD3LightTheme.colors,
      primary: Colors.light.accentColor,
      onPrimary: '#ffffff',
      primaryContainer: Colors.light.accentColorLight,
      onPrimaryContainer: Colors.light.accentColor,
      secondary: Colors.light.textSecondary,
      onSecondary: '#ffffff',
      secondaryContainer: '#e3dfd8',
      onSecondaryContainer: Colors.light.textSecondary,
      tertiary: Colors.light.infoColor,
      onTertiary: '#ffffff',
      tertiaryContainer: '#c8e6ff',
      onTertiaryContainer: Colors.light.infoColor,
      error: Colors.light.dangerColor,
      onError: '#ffffff',
      errorContainer: '#ffedea',
      onErrorContainer: Colors.light.dangerColor,
      background: Colors.light.backgroundPrimary,
      onBackground: Colors.light.textPrimary,
      surface: Colors.light.backgroundSecondary,
      onSurface: Colors.light.textPrimary,
      surfaceVariant: '#f5f5f5',
      onSurfaceVariant: Colors.light.textSecondary,
      outline: Colors.light.borderColor,
      outlineVariant: '#dadce0',
      // Custom colors that can be used with components directly
      text: Colors.light.textPrimary,
      textSecondary: Colors.light.textSecondary,
      accent: Colors.light.accentColor,
      border: Colors.light.borderColor,
      success: Colors.light.successColor,
      warning: Colors.light.warningColor,
      info: Colors.light.infoColor,
    },
  },
  dark: {
    ...MD3DarkTheme,
    colors: {
      ...MD3DarkTheme.colors,
      primary: Colors.dark.accentColor,
      onPrimary: '#ffffff',
      primaryContainer: Colors.dark.accentColorLight,
      onPrimaryContainer: '#ffffff',
      secondary: Colors.dark.textSecondary,
      onSecondary: '#ffffff',
      secondaryContainer: '#333340',
      onSecondaryContainer: Colors.dark.textSecondary,
      tertiary: Colors.dark.infoColor,
      onTertiary: '#ffffff',
      tertiaryContainer: '#003548',
      onTertiaryContainer: '#c8e6ff',
      error: Colors.dark.dangerColor,
      onError: '#ffffff',
      errorContainer: '#5c160e',
      onErrorContainer: '#ffedea',
      background: Colors.dark.backgroundPrimary,
      onBackground: Colors.dark.textPrimary,
      surface: Colors.dark.backgroundSecondary,
      onSurface: Colors.dark.textPrimary,
      surfaceVariant: '#2c2c35',
      onSurfaceVariant: Colors.dark.textSecondary,
      outline: Colors.dark.borderColor,
      outlineVariant: '#444450',
      // Custom colors
      text: Colors.dark.textPrimary,
      textSecondary: Colors.dark.textSecondary,
      accent: Colors.dark.accentColor,
      border: Colors.dark.borderColor,
      success: Colors.dark.successColor,
      warning: Colors.dark.warningColor,
      info: Colors.dark.infoColor,
    },
  },
};
