version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - cd rent_house_server
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building Django app"
      # - python manage.py collectstatic --noinput
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - rent_house_server/**/*
    - appspec.yml
    - scripts/*